//////////// MAIN NUMERIC CONSTANTS ////////////

const CACHE_DURATION_MS = 10 * 60 * 1000 // 10 minutes
const DEFAULT_INTERVAL_MONTHS = 3
const MAX_PERCENTAGE = 200
const MAX_SAFE_NUMBER = 1000000000000 // Billon (Short scale) or Thousand Million (Long scale)
const MAX_STRING_SIZE_DESCRIPTION = 800
const MAX_STRING_SIZE_TITLE = 200
const MIN_PERCENTAGE = -99.99

const Constant = {
    CACHE_DURATION_MS,
    DEFAULT_INTERVAL_MONTHS,
    MAX_PERCENTAGE,
    MAX_SAFE_NUMBER,
    MAX_STRING_SIZE_DESCRIPTION,
    MAX_STRING_SIZE_TITLE,
    MIN_PERCENTAGE,
}

export default Constant
